# Generated by Django 2.2.3 on 2019-07-20 19:15

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mozio_providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeojson',
            name='jeojson',
            field=jsonfield.fields.JSONField(max_length=50),
        ),
    ]
