# Generated by Django 2.2.3 on 2019-07-20 23:01

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mozio_providers', '0002_auto_20190720_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeojson',
            name='jeojson',
            field=jsonfield.fields.JSONField(default="{ 'key': 'value'}"),
        ),
    ]
